version: "3.7"
services:
  web:
    image: ghcr.io/hugofara/lwt:master
    container_name: lwt
    depends_on:
      - db
    links:
      - db
    volumes:
      - ${WEB_MEDIA_PATH}:/var/www/html/lwt/media
    ports:
      - "${WEB_PORT}:80"
    restart: unless-stopped
  db:
    container_name: lwt_db
    environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: "no"
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    hostname: ${DB_HOSTNAME}
    image: mariadb:10.7
    restart: unless-stopped
    volumes:
        - ${DB_DATA_PATH}:/var/lib/mysql
